### ISSUE TITLE
Need builded firmware

### ISSUE THREAD

**Issue by Lenny-Lee-ustb** [rm-controls/rm_usb2can#1]

**Comment by ZhuYanzhen1** [comment]
@Lenny-Lee-ustb Now I have released the compiled firmware to [Release](https://github.com/rm-controls/rm_usb2can/releases). The latest compiled firmware is currently available for download by [clicking here](https://github.com/rm-controls/rm_usb2can/releases/download/firmware_v1_0/candleLight.bin).

**Comment by Lenny-Lee-ustb** [comment]
Thanks!!
